AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  line-chatbot-genai

  Sample SAM Template for line-chatbot-genai

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Parameters:
  ChannelAccessToken:
    Type: String
    Default: 'xxx'

  ChannelSecret:
    Type: String
    Default: 'yyy'

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Environment:
      Variables:
        Channel_access_token      : !Ref ChannelAccessToken
        Channel_secret            : !Ref ChannelSecret
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON


Resources:
  LineChatFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: line_chatbot_genai/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Events:
        LineChat:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /webhook
            Method: POST

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/webhook/"
  LineChatFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt LineChatFunction.Arn
  LineChatFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt LineChatFunctionRole.Arn
